
data_cfg:
  dataset_name: Scoliosis1K
  dataset_root: /mnt/c/Users/gtu/Desktop/OpenGait/datasets/Scoliosis1K/scoliosis1k-dataset/Scoliosis1K-sil-pkl
  dataset_partition: ./datasets/Scoliosis1K/Scoliosis1K_Clean.json
  num_workers: 1
  remove_no_gallery: false
  test_dataset_name: Scoliosis1K

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: /mnt/c/Users/gtu/Desktop/OpenGait/output/Scoliosis1K/ScoNet/ScoNet_Clean/checkpoints/ScoNet_Clean-20000.pt
  save_name: ScoNet_Test_Clean
  eval_func: evaluate_scoliosis
  sampler:
    batch_shuffle: false
    batch_size: 1
    sample_type: all_ordered
    frames_all_limit: 720
  metric: euc
  transform:
    - type: BaseSilCuttingTransform

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true
    class_weights: [1.0, 1.62]

model_cfg:
  model: ScoNet
  backbone_cfg:
    type: ResNet9
    block: BasicBlock
    channels: [64, 128, 256, 512]
    layers: [1, 1, 1, 1]
    strides: [1, 2, 2, 1]
    maxpool: false
  SeparateFCs:
    in_channels: 512
    out_channels: 256
    parts_num: 16
  SeparateBNNecks:
    class_num: 2
    in_channels: 256
    parts_num: 16
  bin_num: [16]

optimizer_cfg:
  lr: 0.001
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: [10000, 15000]
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  fix_BN: false
  with_test: true
  log_iter: 20
  restore_ckpt_strict: true
  restore_hint: /mnt/c/Users/gtu/Desktop/OpenGait/output/Scoliosis1K/ScoNet/ScoNet_Clean/checkpoints/ScoNet_Clean-20000.pt
  save_iter: 1000
  save_name: ScoNet_Test_Clean
  sync_BN: true
  total_iter: 20000
  sampler:
    batch_shuffle: true
    batch_size: [4, 4]
    frames_num_fixed: 30
    sample_type: fixed_unordered
    type: TripletSampler
  transform:
    - type: BaseSilCuttingTransform
